# Generated by Django 3.1.5 on 2021-03-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('my_pic', models.ImageField(blank=True, null=True, upload_to='my_pic/%Y/%m/%d')),
                ('mini_bio', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('addr', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d')),
                ('tools', models.CharField(max_length=200)),
                ('demo', models.URLField()),
                ('github', models.URLField()),
                ('show_in_slider', models.BooleanField(default=False)),
                ('person', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portfol.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=10)),
                ('person', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portfol.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=10)),
                ('person', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portfol.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('link', models.URLField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfol.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='competence/%Y/%m/%d')),
                ('person', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portfol.personalinfo')),
            ],
        ),
    ]
