# Generated by Django 3.1.5 on 2021-03-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfol.personalinfo'),
        ),
    ]
