# Generated by Django 3.1.5 on 2021-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0004_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='mini_bio',
        ),
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='link/%Y/%m/%d'),
        ),
    ]
