# Generated by Django 3.1.5 on 2021-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0005_auto_20210316_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='show_in_slider',
            field=models.CharField(max_length=5),
        ),
    ]
