# Generated by Django 3.1.5 on 2021-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0006_auto_20210318_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
